[package]
name = "seniorproject"
version = "0.1.0"
edition = "2021"

[dependencies]
image = "0.25.4"
rayon = "1.10.0"
native-dialog = "0.7.0"
[dependencies.sdl2]
version = "*"
default-features = false
features = ["ttf", "image"]
